---
name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pytest:
    runs-on: ${{ matrix.runs_on }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
          # error: the configured Python interpreter version (3.14) is newer
          # than PyO3's maximum supported version (3.13)
          # - "3.14"
        runs_on:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run pytest
        run: |
          uv run --frozen pytest

      - name: Check Procfile
        run: |
          uv run honcho check

      - name: Run the process (Windows)
        if: runner.os == 'Windows'
        run: |
            $process = Start-Process "uv" -ArgumentList "run", "honcho", "start" `
                        -NoNewWindow -PassThru
            Start-Sleep -Seconds 10

            $headers = @{
              "Accept" = "application/json"
            }
            $body = @{ text = "こんにちは" } | ConvertTo-Json

            try {
                $body = @{ text = "こんにちは" } | ConvertTo-Json
                $res = Invoke-RestMethod -Uri "http://127.0.0.1:8000/analyze_tokens" `
                                         -Method Post -Body $body `
                                         -ContentType "application/json" `
                                         -Headers $headers

                if ($res.tokens.Count -ge 1) {
                    Write-Host "Success: $($res.tokens.Count) tokens found."
                } else {
                    throw "No tokens found in response."
                }
            } finally {
              Stop-Process -Id $process.Id -Force
            }

      - name: Run the process (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          uv run honcho start &
          SERVER_PID=$!
          sleep 10

          RESPONSE=$(curl -sS -X POST http://127.0.0.1:8000/analyze_tokens \
            -H "Content-Type: application/json" \
            -H "Accept: application/json" \
            -d '{"text": "こんにちは"}')

          TOKEN_COUNT=$(echo "$RESPONSE" | jq '.tokens | length')

          echo "Found $TOKEN_COUNT tokens."

          if [ "$TOKEN_COUNT" -gt 0 ]; then
            echo "Success: Tokens found."
            kill $SERVER_PID
            exit 0
          else
            echo "Error: No tokens found."
            kill $SERVER_PID
            exit 1
          fi
